version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -proot -e 'SHOW databases'"
      interval: 5s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=movies
    command: bash -c "npx sequelize db:migrate && npm start"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
