version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: movies
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql